# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'parkingwatchdog' do
    pod 'GoogleAPIClient/Core', '~> 1.0.2'
    pod 'GTMOAuth2', '~> 1.1.0'
end